package com.ezotex.standard.service;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import com.ezotex.standard.dto.AddressListDTO;
import com.ezotex.standard.dto.CalenderDTO;
import com.ezotex.standard.dto.CompanyDTO;
import com.ezotex.standard.dto.DeptDTO;
import com.ezotex.standard.dto.EmpDTO;
import com.ezotex.standard.dto.InfomationDTO;
import com.ezotex.standard.dto.PositionDTO;
import com.ezotex.standard.dto.ProductCategoryDTO;
import com.ezotex.standard.dto.ProductListInfoDTO;
import com.ezotex.standard.dto.ProductOptionDTO;
import com.ezotex.standard.dto.ResetPasswordDTO;
import com.ezotex.standard.dto.SafetyStockDTO;
import com.ezotex.standard.dto.StorageDTO;
import com.ezotex.standard.dto.StorageProductDTO;

public interface StandardService {
	int searchId(String id);
	List<DeptDTO> deptList();
	List<PositionDTO> positionList();
	int insertEmp(EmpDTO empDTO, AddressListDTO addDTO);
	String idApproval(String id);
	int insertCompany(CompanyDTO companyDTO, AddressListDTO addDTO);
	ResetPasswordDTO findNameEmail(String id);
	int passwordUpdate(String id, String password);
	List<Map<String, Object>> productListAll(ProductListInfoDTO productListInfoDTO);
	List<ProductCategoryDTO> categoryLclas();
	List<ProductCategoryDTO> categorySclas(String lclas);
	int getCount(ProductListInfoDTO productListInfoDTO);
	List<ProductListInfoDTO> unitNameList();
	int ProductInfoInsert(ProductListInfoDTO productListInfoDTO);
	List<ProductCategoryDTO> productCategory(String productCode);
	int productCategoryInsert(List<ProductCategoryDTO> productCategoryDTO);
	List<CompanyDTO> searchCom(String companyName);
	List<ProductOptionDTO> optionSizeList();
	List<ProductOptionDTO> productOption(String productCode);
	int UpdateOption(List<ProductOptionDTO> productOptionDTO);
	List<StorageDTO> storageList();
	List<StorageDTO> storageInfoList(String storageCode);
	int storageVl(String storageInfoCode);
	int insertStorage(String storageName);
	int updateStorage(StorageDTO storageDTO);
	int insertStorageInfo(StorageDTO storageDTO);
	int updateStorageInfo(StorageDTO storageDTO);
	List<StorageProductDTO> StorageProductList(StorageDTO storageDTO);
	List<SafetyStockDTO> SafetyStockList(String productCode);
	int updateSafety(SafetyStockDTO safetyStockDTO);
	List<Map<String, Object>> infomationList();
	int getInfomationCount();
	InfomationDTO infomationNum(int num);
	int infomationUpdate(int num, String title, String content);
	int infomationInsert(String userCode, String title, String content);
	int storageInfoColUpdate(int num, String storageCode, int selectCol);
	int storageInfoRowUpdate(int num, String storageCode, int selectRow);
	List<CalenderDTO> calendarInfo();
	List<CalenderDTO> calendarCount();
	List<ProductListInfoDTO> mainProductImg();
	Map<String, BigDecimal> mainTodayCount();
}
